name: CI / CD for Angular
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: macos-latest
    steps:
      - name: Node Version
        run: node --version

      - name: NPM Version
        run: npm --version
        
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: npm i

      - name: Build
        run: npm run build
        
      - name: Deploy 
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          branch: gh-pages
          folder: dist/angular-website
